### ISSUE TITLE
adding new function 

### ISSUE THREAD

**Issue by dex1670** [dex1670/SQAStudent_19F19551#1]
I want to add a function to calculate the discount if the total sale is more than 100 will be given a 10% discount if less there is no discount

**Comment by Ibrahxm** [comment]
public class Main
{
    
	public static void main(String[] args) {
	    priceafterdiscount price = new priceafterdiscount();
	    price.assign(120,0.10);
	    price.calcPrice();
	    price.display();
	}
	
}
class priceafterdiscount{
    double Totale_price, discount, totalePriceafterDiscount;
    void assign(double a, double b){
	    Totale_price=a;
	    discount = b;
	}
	void calcPrice(){
	    if (Totale_price >= 100){
	    totalePriceafterDiscount = Totale_price*discount;
	    
	    } else{
	        Totale_price = Totale_price;
	    }
	    
	
	    
	}
	void display(){
	    System.out.println(totalePriceafterDiscount);
	}
}
I just add if else statement to differentiate the total price.
