### ISSUE TITLE
Add new Fucntion 

### ISSUE THREAD

**Issue by dex1670** [dex1670/SQAStudent_19F19551#3]
I want to add a new function that will calculate the discount if it is more than 100 give them a discount of 5%

**Comment by SayedhassanUddin** [comment]
public class Main
{
    
	public static void main(String[] args) {
	    priceafterdiscount price = new priceafterdiscount();
	    price.assign(1922,0.10);
	    price.calcPrice();
	    price.display();
	}
	
}
class priceafterdiscount{
    double Totale_price, discount, totalePriceafterDiscount;
    void assign(double a, double b){
	    Totale_price=a;
	    discount = b;
	}
	void calcPrice(){

           if (Totale_price > 100){
	    totalePriceafterDiscount = Totale_price*0.5;
             }
           else{
           System.out.println("there is no discount");
                    }
 
	    
	}
	void display(){
	    System.out.println(totalePriceafterDiscount);
	}
}
